version: '3.3'
services:
  kimkommt:
    volumes:
      - '.:/srv/jekyll'
      - './vendor/bundle:/usr/local/bundle'
    environment:
      - JEKYLL_ENV=development
    ports:
      - '4000:4000'
    image: jekyll/jekyll
    command: jekyll serve