version: '3.3'
services:
  jekyll:
    volumes:
      - '.:/srv/jekyll'
      - './vendor/bundle:/usr/local/bundle'
    environment:
      - JEKYLL_ENV=development
    ports:
      - '4000:4000'
    image: jekyll/jekyll:3.8
    command: jekyll serve