#-------------------------------
# General Site Settings

title: kim kommt
logo:
author: Gabriele Reuter
description: this is meta description
email: post@gabrielereuter.de
phone: +49 176 10021740
address: address
copyright: Copyright &copy; 2021 snizzleorg adapted from [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)
headerimage: assets/images/illustrations/Header.png

menu:
- {name: über Kim, link: '/about'}
- {name: Salon Raumverstehen, link: '/salon'}
- {name: Team, link: '/team'}
- {name: Kim Mieten, link: '/mieten'}
- {name: Newsletter, link: '/contact'}



#-------------------------------
# Hero Section

hero:
  hero-title: <i>K</i>ultur<i>I</i>nstitut<i>M</i>obil

social:
##- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "https://instagram.com/kulturinstitutmobil"}
##- {icon: "ti-dribbble", link: "#"}
## - {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  KIM – das KulturInstitutMobil taucht an verschiedenen Plätzen im Stadtraum auf. Ursprünglich war KIM ein Lastenrad, das von der Ausbildungsinitiative ARRIVO BERLIN zum KulturInstitutMobil umgebaut wurde. Es bringt wetterfeste, multifunktionale Möbel mit (Sitzgelegenheiten, Stehtische, Flipcharts, einfache Designelemente, batteriebetriebenes Licht und Ton) und eignet sich für jegliche Art von kulturellen Veranstaltungen, die an bisher unerschlossenen Orten im Stadtraum stattfinden. KIM ist autark und improvisationsfähig und kann sich allen Umständen der Unplanbarkeit bestens anpassen. 
blurb-btn-link: '/kimkommt/about'
blurb-btn-name: über uns


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Gabriele Reuter"
    image : "assets/images/team/gabriele.jpeg"
    designation : "Konzept"
    link: "http://gabrielereuter.de"
    description : "
    Gabriele Reuter ist Choreografin / Performerin und Urbanistin. Ihre Choreografien mit den Schwerpunktthemen Raum und Akustik/Sound wurden auf verschiedenen internationalen Festivals gezeigt, u.a. Nottdance (GB), Springdance (NL), idans (TU). 
    
    Ihre künstlerische Praxis versteht sie als Vermittlungsarbeit, die an der Schnittstelle von Choreografie, Stadtplanung und partizipativen Gruppenprozessen stattfindet. Als Moderatorin und Prozessbegleiterin im Bereich Agile und Design Thinking fokussiert sie sich auf  Wissenstransfer und Teamarbeit. 
    
    Gabriele unterrichtete seit 2003 international Kontaktimprovisation, Zeitgenössischen Tanz und Komposition an Tanzinstitutionen und Universitäten. Ihre choreografischen Arbeiten und interdisziplinären Projekte wurden international auf Festivals wie nottdance Nottingham, dem Springdance Festival Utrecht, SpringLoaded at The Place London und idans Istanbul gezeigt.
    " 
    
  - title : "Zoé Duflot"
    image : "assets/images/team/zoe.jpeg"
    designation : "Kommunikation"
    description : "Zoé Duflot studierte Marketing und Kulturmanagement an der ESCEM Business School in Tours, sowie in Paris, Belfast und München. Geboren in Frankreich, lebt sie seit 2013 in Berlin. Sie ist seit 2015 bei der Tanzfabrik Berlin für die Kommunikation und Koordination der Workshops zuständig. Für die Berlinale war sie von 2016 bis 2020 für die Gästebetreuung und andere organisatorische Aufgaben zuständig. Bei der Documenta 14 in Kassel war sie im Team des Presse- und Informationszentrums. Darüber hinaus hat sie 2019 beim Steirischen Herbst in Graz als Kommunikationsassistenz gearbeitet. Daneben ist sie für verschiedene kleinere internationale Film- und Kunstfestivals im Bereich Organisation tätig."
    
  - title : "Veronika Wagner"
    image : "assets/images/team/veronika.jpeg"
    designation : "Produktion"
    link : "http://www.veronikawagner.de"
    description : "Veronika Wagner studierte Theaterwissenschaft und Iranistik an der Ludwig-Maximilians-Universität in München. Sie schreibt für die Neue Deutsche Biografie und gibt am Institut für Theaterwissenschaft der Ludwig-Maximilians-Universität Seminare zum Thema Kulturvermittlung, Tanz- und Theaterhistoriografie. 

    Darüber hinaus arbeitet sie als Dramaturgin und Produktionsleiterin in der freien Szene. Für den fachbetrieb rita grechen, das SPIELART Theater Festival, die Choreografinnen Sandra Chatterjee und Lena Grossmann und die Regisseurinnen Verena Regensburger und Anina Jendreyko war und ist sie als Dramaturgin und Produktionsleiterin tätig. 

    2020 war sie für Joint Adventures im Organisationsteam der Tanzplattform Deutschland 2020 und als Dramaturgin bei der Tanzwerkstatt Europa.
    " 

  - title : "Sophie Jahnke"
    image : "assets/images/team/member-3.png"
    designation : "Grafik"







#-------------------------------
# Skills Section

#skills-title: Skills
#skills:
#- {name: Web Design, color: '#fdb157', value: '90%'}
#- {name: Logo Design, color: '#9473e6', value: '60%'}
#- {name: After Effects, color: '#bdecf6', value: '80%'}
#- {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

#experience-title: Experience
#experience:
#- {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
#- {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
#- {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}
#

#-------------------------------
# Education Section

#education-title: Education
#education:
#- {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
#- {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
#- {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
#- {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

#services-title: Services
#services:
#- {
#    name: UI Design,
#    icon: ti-palette,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: # Add true to select section
#  }
#- {
#    name: UX Design,
#    icon: ti-vector,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: true # Add true to select section
#  }
#- {
#    name: Interaction Design,
#    icon: ti-panel,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: # Add true to select section
#  }



#-------------------------------
# Projekte (Section and Page)

# Projekte Home Section
projekte-home-items:
  - image : "assets/images/salon/210219_KIM-Salon_Teaser.png"
    url: "salon"
    excerpt: "
    Der Salon Raumverstehen sieht den Stadtraum als beweglichen Organismus. Durch Tanz werden Körper und Ort in eine unmittelbare sinnliche Beziehung zueinander gesetzt. So werden die sichtbaren und unsichtbaren Machtgefüge städtischer Räume, der alltägliche Kampf um Lebensraum  und Lebensqualität und die empfindlichen Dynamiken zwischen unterschiedlichsten Nutzergruppen des  Ortes neu verhandelt. Kurzvorträge von Expert*innen, praktische Übungen mit dem Publikum, kurze Performances und gemeinsam Nachdenken und Diskutieren. Es geht darum, gemeinsam Raum zu verstehen.
    "


#-------------------------------
# Sponsor Slider Section

sponsor-slider-items:
  - logo: "assets/images/sponsor-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/sponsor-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/sponsor-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/sponsor-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/sponsor-logo/client-logo-5.svg"
    url: "#"

  - logo: "assets/images/sponsor-logo/tf-logo-schule-2020-web.jpg"
    url: "#"

  - logo: "assets/images/sponsor-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/sponsor-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/sponsor-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/sponsor-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/sponsor-logo/client-logo-5.svg"
    url: "#"

  - logo: "assets/images/sponsor-logo/tf-logo-schule-2020-web.jpg"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Kontakt
contact-email: post@gabrielereuter.de

