#-------------------------------
# General Site Settings

title: kim kommt
logo:
author: Gabriele Reuter
description: this is meta description
email: post@gabrielereuter.de
phone: +49 176 10021740
address: address
copyright: Copyright &copy; 2021 snizzleorg adapted from [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)
headerimage: assets/images/illustrations/Header.png

menu:
- {name: über Kim, link: '/about'}
- {name: Salon Raumverstehen, link: '/salon'}
- {name: Team, link: '/team'}
- {name: Kim Mieten, link: '/mieten'}
- {name: Newsletter, link: '/contact'}



#-------------------------------
# Hero Section

hero:
  hero-title: <i>K</i>ultur<i>I</i>nstitut<i>M</i>obil

social:
- {icon: "ti-facebook", link: "https://www.facebook.com/kulturinstitutmobil"}
- {icon: "ti-instagram", link: "https://instagram.com/kulturinstitutmobil"}
##- {icon: "ti-dribbble", link: "#"}
## - {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  KIM – das KulturInstitutMobil ist ein mobiler Veranstaltungsort, der an unterschiedlichen Orten von Berlin Begegnung, künstlerische Arbeit und gemeinsames Nachdenken über Stadt fördert. KIM ist eigentlich ein Lastenrad, das nach einer Idee von Gabriele Reuter von der Übungswerkstätte ARRIVO BERLIN in der Schlesischen 27 im Frühling 2021 zum KulturInstitutMobil umgebaut wird. Es bringt wetterfeste, multifunktionale Möbel mit und eignet sich für jegliche Art von kulturellen Veranstaltungen, die an bisher unerschlossenen Orten im Stadtraum stattfinden. KIM ist autark und improvisationsfähig und kann sich allen Umständen der Unplanbarkeit bestens anpassen. 
  <br>
  Diese Website informiert über den Bau von KIM, über sein Team und die erste Veranstaltungsserie „Salon Raumverstehen“ im Sommer 2021.
blurb-btn-link: '/about'
blurb-btn-name: (mehr über KIM)


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Gabriele Reuter"
    image : "assets/images/team/gabriele.jpeg"
    imagecredit : "©Kaja Strempel, Strempel Photography Services"
    designation : "Konzept"
    link: "http://gabrielereuter.de"
    description : "
    Gabriele Reuter ist Choreografin / Performerin und Urbanistin. Ihre Choreografien mit den Schwerpunktthemen Raum und Akustik/Sound wurden auf verschiedenen internationalen Festivals gezeigt, u.a. Nottdance (GB), Springdance (NL), idans (TU). 
    
    Ihre künstlerische Praxis versteht sie als Vermittlungsarbeit, die an der Schnittstelle von Choreografie, Stadtplanung und partizipativen Gruppenprozessen stattfindet. Als Moderatorin und Prozessbegleiterin im Bereich Agile und Design Thinking fokussiert sie sich auf  Wissenstransfer und Teamarbeit. 
    
    Gabriele unterrichtete seit 2003 international Kontaktimprovisation, Zeitgenössischen Tanz und Komposition an Tanzinstitutionen und Universitäten. Ihre choreografischen Arbeiten und interdisziplinären Projekte wurden international auf Festivals wie nottdance Nottingham, dem Springdance Festival Utrecht, SpringLoaded at The Place London und idans Istanbul gezeigt.
    " 
    
  - title : "Zoé Duflot"
    image : "assets/images/team/zoe.jpeg"
    designation : "Kommunikation & Produktion"
    description : "Zoé Duflot studierte Marketing und Kulturmanagement an der ESCEM Business School in Tours, sowie in Paris, Belfast und München. Geboren in Frankreich, lebt sie seit 2013 in Berlin. Sie ist seit 2015 bei der Tanzfabrik Berlin für die Kommunikation und Koordination der Workshops zuständig. Für die Berlinale war sie von 2016 bis 2020 für die Gästebetreuung und andere organisatorische Aufgaben zuständig. Bei der Documenta 14 in Kassel war sie im Team des Presse- und Informationszentrums. Darüber hinaus hat sie 2019 beim Steirischen Herbst in Graz als Kommunikationsassistenz gearbeitet. Daneben ist sie für verschiedene kleinere internationale Film- und Kunstfestivals im Bereich Organisation tätig."
    
  - title : "Veronika Wagner"
    image : "assets/images/team/veronika.jpeg"
    designation : "Dramaturgie & Produktion"
    link : "http://www.veronikawagner.de"
    description : "Veronika Wagner studierte Theaterwissenschaft und Iranistik an der Ludwig-Maximilians-Universität in München. Sie schreibt für die Neue Deutsche Biografie und gibt am Institut für Theaterwissenschaft der Ludwig-Maximilians-Universität Seminare zum Thema Kulturvermittlung, Tanz- und Theaterhistoriografie. 

    Darüber hinaus arbeitet sie als Dramaturgin und Produktionsleiterin in der freien Szene. Für den fachbetrieb rita grechen, das SPIELART Theater Festival, die Choreografinnen Sandra Chatterjee und Lena Grossmann und die Regisseurinnen Verena Regensburger und Anina Jendreyko war und ist sie als Dramaturgin und Produktionsleiterin tätig. 

    2020 war sie für Joint Adventures im Organisationsteam der Tanzplattform Deutschland 2020 und als Dramaturgin bei der Tanzwerkstatt Europa.
    " 

  - title : "Sophie Jahnke"
    image : "assets/images/team/sophie.jpeg"
    designation : "Grafik"
    link: "http://sophiejahnke.com"
    description: "Sophie Jahnke ist Grafikerin und Illustratorin. Sie kommuniziert verschiedenste Themen des öffentlichen Raums und der Wissensvermittlung mittels nutzerorientiertem Informationsdesign, visuellem Storytelling und der Auswahl und Gestaltung von Print-, Ausstellungs- und Onlineformaten.
    Mit ihrem analytischen Zugang hilft sie Informationen zu strukturieren, zu hierarchisieren und zu priorisieren bevor sie abstrakten Konzepten und Visionen ihren ganz eigenen grafischen Ausdruck gibt. So übersetzt sie einerseits fachplanerisches Vokabular in eine allgemein verständliche Sprache und findet andererseits Bilder für visuell flüchtige Choreografien und Interventionen des Urbanen. Ein spielerisch-ironischer Blick erleichtert den Zugang zu den komplexen Fachthemen & -welten ihrer Arbeiten. 
    Seit über zehn Jahren arbeitet Sophie in synergetischer Partnerschaft mit Landschaftsarchitekt:innen, Stadtplaner:innen und Ausstellungsgestalter:innen. Sie berät Städte wie Bern, Zürich und München bei der bürgernahen Kommunikation ihrer Entwicklungsstrategien, befasst sich mit der Gestaltung kollektiver Erinnerung, plant Besucherinformations- und Orientierungssysteme.
    "

  - title : "Chadi Dalaty"
    image : "assets/images/team/Chadi.png"
    designation : "Technische Leitung"
    link: "http://#"
    description: "Chadi ist Musikproduzent, Sänger und Tontechniker. 2006 schloss der gebürtige Libanese sein Studium an der Scuola Di Alto Perfezionamente Musicale Citta' Di Saluzzo zum Live- und Studio-Tontechniker ab. Anschließend arbeitete er für BH Audio, wo er als Live-Tontechniker, Tonassistent, Monitortechniker und Experte für D&B Beschallungsanlagen für Künstler:innen wie Goran Bregovic, Mike Patton, The Faint, Meredith Monk, Anthony and the Johnsons, Cat Power, Sonic Youth, Mum und viele mehr tätig war. 2006 gründete er seine aktuelle Band YaZeeDee, die Elektro, arabische Einflüsse, Rock- und Weltmusik zusammenführt. Seit 2015 arbeitet Chadi bei YSD Berlin als Produzent und Toningenieur. Darüber hinaus ist er als Haustechniker und Veranstaltungstechniker für die Schlesische 27 tätig. 
KIM unterstützt Chadi als Hausmeister. Außerdem übernimmt er die Tontechnik bei Veranstaltungen und hilft bei der Kommunikation auf Arabisch, Französisch und Italienisch.
    "





#-------------------------------
# Skills Section

#skills-title: Skills
#skills:
#- {name: Web Design, color: '#fdb157', value: '90%'}
#- {name: Logo Design, color: '#9473e6', value: '60%'}
#- {name: After Effects, color: '#bdecf6', value: '80%'}
#- {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

#experience-title: Experience
#experience:
#- {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
#- {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
#- {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}
#

#-------------------------------
# Education Section

#education-title: Education
#education:
#- {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
#- {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
#- {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
#- {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

#services-title: Services
#services:
#- {
#    name: UI Design,
#    icon: ti-palette,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: # Add true to select section
#  }
#- {
#    name: UX Design,
#    icon: ti-vector,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: true # Add true to select section
#  }
#- {
#    name: Interaction Design,
#    icon: ti-panel,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: # Add true to select section
#  }



#-------------------------------
# Projekte (Section and Page)

# Projekte Home Section
projekte-home-items:
  - image : "assets/images/salon/210219_KIM-Salon_Teaser.png"
    url: "salon"
    excerpt: "
    Der Salon Raumverstehen sieht den Stadtraum als beweglichen Organismus. Durch Tanz werden Körper und Ort in eine unmittelbare sinnliche Beziehung zueinander gesetzt. So werden die sichtbaren und unsichtbaren Machtgefüge städtischer Räume, der alltägliche Kampf um Lebensraum  und Lebensqualität und die empfindlichen Dynamiken zwischen unterschiedlichsten Nutzergruppen des  Ortes neu verhandelt. Kurzvorträge von Expert*innen, praktische Übungen mit dem Publikum, kurze Performances und gemeinsam Nachdenken und Diskutieren. Es geht darum, gemeinsam Raum zu verstehen.
    "


#-------------------------------
# Sponsor Slider Section

sponsor-slider-items:

  - logo: "assets/images/sponsor-logo/BKM.png"
    url: "https://www.bundesregierung.de/breg-de/bundesregierung/staatsministerin-fuer-kultur-und-medien"
    
  - logo: "assets/images/sponsor-logo/Neustart.png"
    url: "https://neustartkultur.de/"
    
  - logo: "assets/images/sponsor-logo/NPN.png"
    url: "https://www.jointadventures.net/service/ueber-uns/walter-heun.html"

  - logo: "assets/images/sponsor-logo/arrivo.png"
    url: "https://www.s27.de/portfolio/arrivo/"

  - logo: "assets/images/sponsor-logo/S27.png"
    url: "https://www.s27.de/"

  - logo: "assets/images/sponsor-logo/mondiale.png"
    url: "https://berlin-mondiale.de/de/"

  - logo: "assets/images/sponsor-logo/tf-logo-schule-2020-web.png"
    url: "https://www.tanzfabrik-berlin.de/"
    
#  - logo: "assets/images/sponsor-logo/urbanepraxis.png"
#    url: "https://www.urbanepraxis.berlin"

  - logo: "assets/images/sponsor-logo/BKM.png"
    url: "https://www.bundesregierung.de/breg-de/bundesregierung/staatsministerin-fuer-kultur-und-medien"
    
  - logo: "assets/images/sponsor-logo/Neustart.png"
    url: "https://neustartkultur.de/"
    
  - logo: "assets/images/sponsor-logo/NPN.png"
    url: "https://www.jointadventures.net/service/ueber-uns/walter-heun.html"

  - logo: "assets/images/sponsor-logo/arrivo.png"
    url: "https://www.s27.de/portfolio/arrivo/"

  - logo: "assets/images/sponsor-logo/S27.png"
    url: "https://www.s27.de/"

  - logo: "assets/images/sponsor-logo/mondiale.png"
    url: "https://berlin-mondiale.de/de/"

  - logo: "assets/images/sponsor-logo/tf-logo-schule-2020-web.png"
    url: "https://www.tanzfabrik-berlin.de/"
    
#  - logo: "assets/images/sponsor-logo/urbanepraxis.png"
#    url: "https://www.urbanepraxis.berlin"

#-------------------------------
# Contact Section

contact-title: Kontakt
contact-email: post@gabrielereuter.de

