#-------------------------------
# General Site Settings

title: kim kommt
logo:
author: Gabriele Reuter
description: this is meta description
email: post@gabrielereuter.de
phone: +49 176 10021740
address: 125/A, CA Commercial Area, California, USA
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: über Kim, link: 'about'}
- {name: Projekte, link: 'salon'}
- {name: Termine, link: 'termine'}
- {name: Team, link: 'team'}
- {name: Kim Mieten, link: 'mieten'}
- {name: Newsletter, link: 'contact'}



#-------------------------------
# Hero Section

hero:
  hero-title: <i>K</i>ultur<i>I</i>nstitut<i>M</i>obil

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
##- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  KIM – das KulturInstitutMobil taucht an verschiedenen Plätzen im Stadtraum auf. Ursprünglich war KIM ein Lastenrad, das von der Ausbildungsinitiative ARRIVO BERLIN zum KulturInstitutMobil umgebaut wurde. Es bringt wetterfeste, multifunktionale Möbel mit (Sitzgelegenheiten, Stehtische, Flipcharts, einfache Designelemente, batteriebetriebenes Licht und Ton) und eignet sich für jegliche Art von kulturellen Veranstaltungen, die an bisher unerschlossenen Orten im Stadtraum stattfinden. KIM ist autark und improvisationsfähig und kann sich allen Umständen der Unplanbarkeit bestens anpassen. 
blurb-btn-link: '/kimkommt/about'
blurb-btn-name: über uns


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Gabriele Reuter"
    image : "assets/images/team/member-1.png"
    designation : "Konzept"
    
  - title : "Zoé Duflot"
    image : "assets/images/team/member-2.png"
    designation : "Kommunikation"
    
  - title : "Veronika Wagner"
    image : "assets/images/team/member-3.png"
    designation : "Produktion"

  - title : "Sophie Jahnke"
    image : "assets/images/team/member-3.png"
    designation : "Grafik"

  - title : "Susanne Martin"
    image : "assets/images/team/member-3.png"
    designation : "Konzept"

#-------------------------------
# Skills Section

#skills-title: Skills
#skills:
#- {name: Web Design, color: '#fdb157', value: '90%'}
#- {name: Logo Design, color: '#9473e6', value: '60%'}
#- {name: After Effects, color: '#bdecf6', value: '80%'}
#- {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

#experience-title: Experience
#experience:
#- {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
#- {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
#- {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}
#

#-------------------------------
# Education Section

#education-title: Education
#education:
#- {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
#- {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
#- {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
#- {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

#services-title: Services
#services:
#- {
#    name: UI Design,
#    icon: ti-palette,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: # Add true to select section
#  }
#- {
#    name: UX Design,
#    icon: ti-vector,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: true # Add true to select section
#  }
#- {
#    name: Interaction Design,
#    icon: ti-panel,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: # Add true to select section
#  }



#-------------------------------
# Projekte (Section and Page)

# Projekte Home Section
projekte-home-items:
  - image : "assets/images/salon/210129_KIM_Salon.png"
    url: "salon"
    
#  - image : "assets/images/portfolio/item-2.png"
#    url: "#"
#    
#  - image : "assets/images/portfolio/item-3.png"
#    url: "#"
#    
#  - image : "assets/images/portfolio/item-4.png"
#    url: "#"
#    
#  - image : "assets/images/portfolio/item-5.png"
#    url: "#"


# Projekte Page
projekte-label:
- {
    title : "Salon Raumverstehen",
    type : "Salon"
  }
#- {
#    title : "BRANDING",
#    type : "branding"
#  }
#- {
#    title : "ILLUSTRATION",
#    type : "illustration"
#  }

projekte-items:
  - image : "assets/images/salon/210129_KIM_Salon.png"
    url: "salon"
    projekte-type:
     - type: "Salon"
      
# - image : "assets/images/portfolio/item-2.png"
#    url: "#"
#    portfolio-type:
#      - type: "branding"
#      
#  - image : "assets/images/portfolio/item-3.png"
#    url: "#"
#    portfolio-type:
#      - type: "illustration"
#      
#  - image : "assets/images/portfolio/item-6.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
#      - type: "branding"
      
#  - image : "assets/images/portfolio/item-8.png"
#    url: "#"
#    portfolio-type:
#      - type: "illustration"
      
#  - image : "assets/images/portfolio/item-5.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
      
#  - image : "assets/images/portfolio/item-1.png"
#    url: "#"
#    portfolio-type:
#      - type: "branding"
      
#  - image : "assets/images/portfolio/item-3.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
#      - type: "illustration"
#      - type: "branding"
      
#  - image : "assets/images/portfolio/item-7.png"
#    url: "#"
#    portfolio-type:
#      - type: "illustration"


#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation : "CEO, Funder"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Sponsor Slider Section

sponsor-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Kontakt
contact-email: post@gabrielereuter.de

